### ISSUE TITLE
fragment+ viewpager 实现懒加载

### ISSUE THREAD

**Issue by uty3714** [LRH1993/SmartRecom#1]
//可见，但是并没有加载过
        if (isFragmentVisible && !isFirst) {
            onFragmentVisibleChange(true);
        }

这里的原因是 因为 viewpager 预加载了X个数量的fragment的原因吧，导致最后一个fragment的可见是true，当前页面的可见是false，

我也不确定是不是这个原因，但是我在项目中打印的时候，确实是这个情况。

那么 针对fragment和viewpager 组合的时候 如何实现懒加载呢？--修改v4包下的viewpager的预加载个数吗？

**Comment by LRH1993** [comment]
viewpager预加载 至少会加载左右页面。  可以参考我写的这篇文章，里面有详细解释：http://www.jianshu.com/p/eb81f3692229

**Comment by uty3714** [comment]
好  我看下 谢谢

**Comment by uty3714** [comment]
必须要 下拉刷新一次 才能加载数据吗？  有没有今日头条的 类似效果？

**Comment by uty3714** [comment]
我之前写的 也是 必须下拉刷一次 才会执行数据，但是这样感觉给用户不好的体验。。
