### ISSUE TITLE
Download下来导入AS怎么跑不了啊

### ISSUE THREAD

**Issue by KingsleyDeng** [LRH1993/SmartRecom#3]
Error:(1, 0) startup failed:
build file 'F:\StudyProject\SmartRecom-master\SmartRecom-master\SmartRecom\ThreeRecom\build.gradle': 1: Invalid variable name. Must start with a letter but was: ﻿
. At [1:1]  @ line 1, column 1.
   ﻿// Top-level build file where you can add configuration options common to all sub-projects/modules.
   ^

1 error

<a href="openFile:F:\StudyProject\SmartRecom-master\SmartRecom-master\SmartRecom\ThreeRecom\build.gradle">Open File</a>

**Comment by androidzhangyu** [comment]
@KingsleyDeng 这个博主还玩高冷，不用看他的了，给你74套源码地址：74款APP完整源码！
链接: https://pan.baidu.com/s/1cGLK8u 密码: gqt。
