### ISSUE TITLE
个性化推荐 基于什么算法？

### ISSUE THREAD

**Issue by luboq** [LRH1993/SmartRecom#4]
个人对个性化推荐这块，最感兴趣

项目用的什么算法，做推荐？靶中率如何呢？

豆瓣电影、网易云音乐也有个性化推荐，但效果只能说“及格”，达不到“卓越”呢

所以看到新的个性化推荐，就像了解下

**Comment by LRH1993** [comment]
个性化推荐这块是另一个同学做的。用的是他自己改进过的Slope One算法，不过数据源有点问题。现在项目还没真正用到，准确率感觉还可以。

**Comment by luboq** [comment]
@LRH1993 好哒，谢谢，期待项目完善~
